name: womenco
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  dots_indicator: ^2.1.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - C:\Users\Saif\Desktop\Women CO\womenco\assets\boarding1.png
    - C:\Users\Saif\Desktop\Women CO\womenco\assets\boarding2.png
    - C:\Users\Saif\Desktop\Women CO\womenco\assets\boarding3.png
    - C:\Users\Saif\Desktop\Women CO\womenco\assets\shape.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/AvenirLTStd-Black.otf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700